### PR TITLE
fix early cursed seal locking up the game

### LINKED ISSUE #8: Early Cursed Seal locks up game
Receiving the Cursed Seal in a fresh new game while in the Entrance makes the game lock up for an extended period of time. Assuming that it's taking too long to cull/curse the monster population. This generally shouldn't happen anyway, since the Cursed Seal is in a fixed location in the game, but the game assumes at least 75% of the monster population has been defeated by the time the Cursed Seal can be picked up, which apparently can lead to performance hits if that's not the case.

_Originally posted by @FelicitusNeko in https://github.com/FelicitusNeko/meritous-ap/issues/6#issuecomment-1063298376_

### PR DESCRIPTION
**Pull request by Rnd-Guy**
Fixes #8 

When picking up cursed seal, the curse function does two things:
* Cull 4/5 of enemies 
* Curse 1/5 and place them in one of the visited rooms in the dungeon <-- this is where it locks up

When searching for a room to place a cursed enemy, the game does an infinite loop and only breaks out when it finds a suitable room, and if none exist then it never finishes. This only happens when cursed seal is picked up extremely early and is unlikely to happen under normal play (as you need 75% kills to pick it up generally).

This also opens up a future possibility of reducing the seal requirement.

Boss rooms only trigger on room transition usually, so using this without exploring any rooms is a softlock, I've also forced the boss room to be triggered if we are in the starting room when we call curse.

We can now face the boss instantly (would not recommend 💀)
meritous-early-cursed-seal

### CODE REVIEW

**Comment by FelicitusNeko** [comment]
Let me just say before anything, it's kind of hilarious to see the Entrance turn into the final boss room before my eyes.

File: src/boss.c [hunk 1]
```diff
@@ -474,6 +474,13 @@ void Curse()
   // Every 25th monster becomes a curse. All other monsters are deleted
 
   CurseEnemies();
```
Comment (FelicitusNeko) [inline src/boss.c]: I wonder if we shouldn't just skip culling/cursing if we're already in the boss room.

**Review by FelicitusNeko — CHANGES_REQUESTED** [review]
Just one little optimisation I was able to find, unless it would cause any problems to do so.

File: src/boss.c (hunk 1 above)
Comment (Rnd-Guy) [reply src/boss.c]: That's a good idea! I'll give that a go and see if that breaks anything

**Comment by Rnd-Guy** [comment]
Looks like it works! 
Tested curse still worked outside the start room and is skipped when inside, and boss whoops me just the same 😅

**Review by FelicitusNeko — APPROVED** [review]
